In [46]:
import pandas as pd
import numpy as np
from statsmodels.stats.weightstats import _zconfint_generic
from statsmodels.stats.weightstats import _tconfint_generic
from statsmodels.stats.weightstats import zconfint
from statsmodels.stats.weightstats import *

In [ ]:
data = pd.read_csv("water.txt",sep='	') 

In [ ]:
data

In [ ]:
data.describe()

In [ ]:
1524.147541-2*187.668754/np.sqrt(61)

In [ ]:
data[data['location']=='South'].describe()

In [ ]:
print(1376.807692-2*140.269175/np.sqrt(26),1376.807692+2*140.269175/np.sqrt(26))
print(69.769231-2*40.360682/np.sqrt(26),69.769231+2*40.360682/np.sqrt(26))

In [ ]:
data[data['location']=='North'].describe()

In [ ]:
print(1633.600000-2*136.936911/np.sqrt(35),1633.600000+2*136.936911/np.sqrt(35))
print(30.400000-2*26.134494/np.sqrt(35),30.400000+2*26.134494/np.sqrt(35))

In [ ]:
(1.96/0.1)**2

In [ ]:
data[data.location == 'South'].hardness.mean(), data[data.location == 'South'].hardness.std(ddof=1) / np.sqrt(len(data[data.location == 'South'])), len(data[data.location == 'South']) - 1

In [ ]:
_tconfint_generic(data.mortality.mean(), data.mortality.std(ddof=1) / np.sqrt(len(data)), len(data)-1,0.05, 'two-sided')

In [ ]:
_tconfint_generic(data[data.location == 'South'].mortality.mean(), data[data.location == 'South'].mortality.std(ddof=1) / np.sqrt(len(data[data.location == 'South'])), len(data[data.location == 'South'])-1,0.05, 'two-sided')

In [ ]:
from statsmodels.stats.proportion import proportion_confint
proportion_confint(1, 50, alpha=0.05, method='normal')

In [ ]:
proportion_confint(1, 50, alpha=0.05, method='wilson')

In [ ]:
from scipy.stats import norm
p=0.975
value = norm.ppf(p)
value

In [ ]:
n=0.02
print((np.sqrt(n*(1-n))/(0.01/value))**2)


In [ ]:
import matplotlib.pyplot as plt

x=np.linspace(0,1,10000)
y=(np.sqrt(x*(1-x))/(0.01/value))**2

In [ ]:
plt.plot(x,y)
np.max(y)

In [ ]:
0.02-value*(np.sqrt(0.02*0.98/50))

In [ ]:
norm.ppf(1-(1-0.997)/2)

In [ ]:
p1=104/11037
p2=189/11034

In [ ]:
p2-p1

In [ ]:
p2-p1+value*np.sqrt((p1*(1-p1)/11037)+(p2*(1-p2)/11034))

In [ ]:
a=p1/(1-p1)
b=p2/(1-p2)

In [ ]:
b/a

In [52]:
np.random.seed(0)
def get_bootstrap_samples(data, n_samples):
    indices = np.random.randint(0, len(data), (n_samples, len(data)))
    samples = data[indices]
    return samples
def stat_intervals(stat, alpha):
    boundaries = np.percentile(stat, [100 * alpha / 2., 100 * (1 - alpha / 2.)])
    return boundaries
def chance (a,b):
    p1=(a==1).sum()/a.shape[0]
    p2=(b==1).sum()/b.shape[0]
    c1=p1/(1-p1)
    c2=p2/(1-p2)
    return(c2/c1)

In [ ]:
np.random.seed(0)
p11=np.hstack((np.ones(104),(np.zeros(11037-104))))
p22=np.hstack((np.ones(189),(np.zeros(11034-189))))

In [ ]:
np.random.seed(0)
chance_div = list(map(chance, get_bootstrap_samples(p11, 1000),get_bootstrap_samples(p22, 1000)))

In [ ]:
stat_intervals(chance_div, 0.05)

In [ ]:
from scipy import stats

In [ ]:
stats.binom_test(67, 100, 0.75)

In [ ]:
data2 = pd.read_csv("pines.txt",sep='	')

In [ ]:
x=data2.sn.values
y=data2.we.values

In [ ]:
pines=stats.binned_statistic_2d(x, y,None, bins=5, statistic='count')[0].reshape(25)

In [ ]:
pines.sum()/25

In [ ]:
stats.chisquare(pines, ddof = 0)

In [ ]:
def z(mean, exp, std, n):
    return (mean - exp) / (std/np.sqrt(n))

2 * (1 - stats.norm.cdf(z(9.57,9.5,0.4,160)))

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import 


In [ ]:
data3 = pd.read_csv("diamonds.txt",sep='	')

In [ ]:
data3

In [ ]:
lr=LinearRegression()
rf=RandomForestRegressor(random_state=1)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(data3.drop(['price'], axis=1), data3['price'], random_state=1)

In [ ]:
lr.fit(X_train, y_train)
rf.fit(X_train, y_train)

In [ ]:
lr_pred=lr.predict(X_test)
rf_pred=rf.predict(X_test)

In [ ]:
stats.ttest_rel(np.abs(lr_pred-y_test), np.abs(rf_pred-y_test))
from statsmodels.stats.weightstats import *

In [ ]:
DescrStatsW(np.abs(lr_pred-y_test)- np.abs(rf_pred-y_test)).tconfint_mean()

In [ ]:
p1=10/34
p2=4/16
def proportions_diff_confint_ind(p1, p2, alpha = 0.05):    
    z = scipy.stats.norm.ppf(1 - alpha / 2.)
    left_boundary = (p1 - p2) - z * np.sqrt(p1 * (1 - p1)/ 34 + p2 * (1 - p2)/ 16)
    right_boundary = (p1 - p2) + z * np.sqrt(p1 * (1 - p1)/ 34 + p2 * (1 - p2)/16)
    
    return (left_boundary, right_boundary)
def proportions_diff_z_stat_ind(p1, p2,n1,n2):
    P = float(p1*n1 + p2*n2) / (n1 + n2)
    
    return (p1 - p2) / np.sqrt(P * (1 - P) * (1. / n1 + 1. / n2))
def proportions_diff_z_test(z_stat, alternative = 'two-sided'):
    if alternative not in ('two-sided', 'less', 'greater'):
        raise ValueError("alternative not recognized\n"
                         "should be 'two-sided', 'less' or 'greater'")
    
    if alternative == 'two-sided':
        return 2 * (1 - scipy.stats.norm.cdf(np.abs(z_stat)))
    
    if alternative == 'less':
        return scipy.stats.norm.cdf(z_stat)

    if alternative == 'greater':
        return 1 - scipy.stats.norm.cdf(z_stat)

In [ ]:
import scipy
proportions_diff_confint_ind(p1, p2, alpha = 0.05)

In [ ]:
proportions_diff_z_test(proportions_diff_z_stat_ind(p1, p2,34,16), alternative = 'greater')

In [ ]:
data4 = pd.read_csv("banknotes.txt",sep='	')

In [ ]:
data4.columns

In [ ]:
from sklearn.linear_model import LogisticRegression
lr1=LogisticRegression()
lr2=LogisticRegression()

In [ ]:
X_train1, X_test1, y_train, y_test = train_test_split(data4.drop(['real'], axis=1), data4['real'], random_state=1)
X_train11,X_train12,X_test11,X_test12=X_train1[['X1','X2','X3']],X_train1[['X4','X5','X6']],X_test1[['X1','X2','X3']],X_test1[['X4','X5','X6']]

In [ ]:
lr1.fit(X_train11, y_train)
lr2.fit(X_train12, y_train)

In [ ]:
lr1_pred=lr1.predict(X_test11)
lr2_pred=lr2.predict(X_test12)

In [ ]:
pred1=(lr1_pred==y_test)
pred2=(lr2_pred==y_test)


In [ ]:
def proportions_diff_confint_rel(sample1, sample2, alpha = 0.05):
    z = scipy.stats.norm.ppf(1 - alpha / 2.)
    sample = list(zip(sample1, sample2))
    n = len(sample)
        
    f = sum([1 if (x[0] == 1 and x[1] == 0) else 0 for x in sample])
    g = sum([1 if (x[0] == 0 and x[1] == 1) else 0 for x in sample])
    
    left_boundary = float(f - g) / n  - z * np.sqrt(float((f + g)) / n**2 - float((f - g)**2) / n**3)
    right_boundary = float(f - g) / n  + z * np.sqrt(float((f + g)) / n**2 - float((f - g)**2) / n**3)
    return (left_boundary, right_boundary)
def proportions_diff_z_stat_rel(sample1, sample2):
    sample = list(zip(sample1, sample2))
    n = len(sample)
    
    f = sum([1 if (x[0] == 1 and x[1] == 0) else 0 for x in sample])
    g = sum([1 if (x[0] == 0 and x[1] == 1) else 0 for x in sample])
    
    return float(f - g) / np.sqrt(f + g - float((f - g)**2) / n )
def proportions_diff_z_test(z_stat, alternative = 'two-sided'):
    if alternative not in ('two-sided', 'less', 'greater'):
        raise ValueError("alternative not recognized\n"
                         "should be 'two-sided', 'less' or 'greater'")
    
    if alternative == 'two-sided':
        return 2 * (1 - scipy.stats.norm.cdf(np.abs(z_stat)))
    
    if alternative == 'less':
        return scipy.stats.norm.cdf(z_stat)

    if alternative == 'greater':
        return 1 - scipy.stats.norm.cdf(z_stat)

In [ ]:
proportions_diff_z_test(proportions_diff_z_stat_rel(pred1, pred2), alternative = 'two-sided')

In [ ]:
proportions_diff_confint_rel(pred1, pred2, alpha = 0.05)

In [ ]:
def z(mean, exp, std, n):
    return (mean - exp) / (std/np.sqrt(n))

1 - stats.norm.cdf(z(541.4,525,100,100))

In [ ]:
1 - stats.norm.cdf(z(541.5,525,100,100))

In [73]:
m0=200
x=np.array([49,58,75,110,112,132,151,276,281,362])
stats.wilcoxon(x-m0)

WilcoxonResult(statistic=17.0, pvalue=0.2845026979112075)

In [76]:
x1=[22,22,15,13,19,19,18,20,21,13,13,15]
x2=[17,18,18,15,12,4,14,15,10]
stats.mannwhitneyu(x1, x2,alternative='greater')


MannwhitneyuResult(statistic=81.0, pvalue=0.02900499272087373)

In [42]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [48]:
zconfint(x1)
zconfint(x2)

(15.503260501590582, 19.49673949840942)

(10.726720689856585, 16.606612643476748)

In [61]:
data5 = pd.read_csv("challenger.txt",sep='	') 
data5.columns
data5
t0=data5[data5['Incident']==0]['Temperature'].values
t1=data5[data5['Incident']==1]['Temperature'].values
t0
t1

Index(['Unnamed: 0', 'Temperature', 'Incident'], dtype='object')

Unnamed: 0  Temperature  Incident
0    Apr12.81         18.9         0
1    Nov12.81         21.1         1
2    Mar22.82         20.6         0
3    Nov11.82         20.0         0
4    Apr04.83         19.4         0
5    Jun18.83         22.2         0
6    Aug30.83         22.8         0
7    Nov28.83         21.1         0
8    Feb03.84         13.9         1
9    Apr06.84         17.2         1
10   Aug30.84         21.1         1
11   Oct05.84         25.6         0
12   Nov08.84         19.4         0
13   Jan24.85         11.7         1
14   Apr12.85         19.4         0
15   Apr29.85         23.9         0
16   Jun17.85         21.1         0
17   Jul29.85         27.2         0
18   Aug27.85         24.4         0
19   Oct03.85         26.1         0
20   Oct30.85         23.9         1
21   Nov26.85         24.4         0
22   Jan12.86         14.4         1

array([18.9, 20.6, 20. , 19.4, 22.2, 22.8, 21.1, 25.6, 19.4, 19.4, 23.9,
       21.1, 27.2, 24.4, 26.1, 24.4])

array([21.1, 13.9, 17.2, 21.1, 11.7, 23.9, 14.4])

In [69]:
def dif (a,b):
    m1=a.mean()
    m2=b.mean()
    return(m1-m2)
np.random.seed(0)
dif = list(map(dif, get_bootstrap_samples(t0, 1000),get_bootstrap_samples(t1, 1000)))
stat_intervals(dif, 0.05)

t0_mean=list(map(np.mean, get_bootstrap_samples(t0, 1000)))
t1_mean=list(map(np.mean, get_bootstrap_samples(t1, 1000)))


array([1.42299107, 7.93861607])

In [80]:
np.random.seed(0)
def permutation_t_stat_ind(sample1, sample2):
    return np.mean(sample1) - np.mean(sample2)
def get_random_combinations(n1, n2, max_combinations):
    index = list(range(n1 + n2))
    indices = set([tuple(index)])
    for i in range(max_combinations - 1):
        np.random.shuffle(index)
        indices.add(tuple(index))
    return [(index[:n1], index[n1:]) for index in indices]
def permutation_zero_dist_ind(sample1, sample2, max_combinations = None):
    joined_sample = np.hstack((sample1, sample2))
    n1 = len(sample1)
    n = len(joined_sample)
    
    if max_combinations:
        indices = get_random_combinations(n1, len(sample2), max_combinations)
    else:
        indices = [(list(index), list(filter(lambda i: i not in index, range(n)))) \
                    for index in itertools.combinations(range(n), n1)]
    
    distr = [joined_sample[list(i[0])].mean() - joined_sample[list(i[1])].mean() \
             for i in indices]
    return distr
def permutation_test(sample, mean, max_permutations = None, alternative = 'two-sided'):
    if alternative not in ('two-sided', 'less', 'greater'):
        raise ValueError("alternative not recognized\n"
                         "should be 'two-sided', 'less' or 'greater'")
    
    t_stat = permutation_t_stat_ind(sample, mean)
    
    zero_distr = permutation_zero_dist_ind(sample, mean, max_permutations)
    
    if alternative == 'two-sided':
        return sum([1. if abs(x) >= abs(t_stat) else 0. for x in zero_distr]) / len(zero_distr)
    
    if alternative == 'less':
        return sum([1. if x <= t_stat else 0. for x in zero_distr]) / len(zero_distr)

    if alternative == 'greater':
        return sum([1. if x >= t_stat else 0. for x in zero_distr]) / len(zero_distr)
        
permutation_test(t0, t1, max_permutations = 10000)

0.007